databases:
  - name: mysql2
    plan: starter
    env:
      MYSQL_DATABASE: ideator_production
      MYSQL_USER: root
      MYSQL_PASSWORD: Pankaj@123

services:
  - type: web
    name: ideator
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s -p $PORT -e $RAILS_ENV"
    env:
      RAILS_MASTER_KEY: fromFile:config/master.key
      DATABASE_URL: mysql2://root:Pankaj@123@localhost/ideator_production?reconnect=true&encoding=utf8mb4&pool=5
