databases:
  - name: mysql2
    ipAllowList: []
    databaseName: ideator
    user: ideator
    password: <%= ENV["Pankaj@123"] %>
    connectionLimit: 20

services:
  - type: web
    name: ideator
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s -p $PORT -e $RAILS_ENV"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysql2
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
